apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: demo-tradr-channel
  namespace: tekton-pipelines
spec:
  sourceNamespaces:
  - tekton-pipelines
  type: Namespace
  pathname: demo-tradr-channel
  gates:
    annotations:
      dev-ready: approved
