apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-tradr-subscription
  namespace: demo-mcm-resources
  labels:
    purpose: demo-tradr
spec:
  channel:  tekton-pipelines/demo-tradr-channel
  placement:
    placementRef:
      name: demo-tradr-placementrule
      kind: PlacementRule
      group: apps.open-cluster-management.io
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: demo-tradr-mcm
