apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-tradr-application
  namespace: demo-mcm-resources
spec:
  selector:
    matchLabels:
      purpose: demo-tradr
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
